# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
python -m lerobot.record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, camera_index: 0, width: 640, height: 480}}" \
    --robot.id=black \
    --teleop.type=so100_leader \
    --teleop.port=/dev/tty.usbmodem58760431551 \
    --teleop.id=blue \
    --dataset.repo_id=aliberts/record-test \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube"
```
"""

import json
import logging
import time
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
from pprint import pformat

import numpy as np
import rerun as rr

from lerobot.common.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.common.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.common.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.common.datasets.image_writer import safe_stop_image_writer
from lerobot.common.datasets.lerobot_dataset import LeRobotDataset
from lerobot.common.datasets.utils import build_dataset_frame, hw_to_dataset_features
from lerobot.common.policies.factory import make_policy
from lerobot.common.policies.pretrained import PreTrainedPolicy
from lerobot.common.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    koch_follower,
    make_robot_from_config,
    so100_follower,
    so101_follower,
)
from lerobot.common.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    make_teleoperator_from_config,
)
from lerobot.common.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.common.utils.robot_utils import busy_wait
from lerobot.common.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.common.utils.visualization_utils import _init_rerun
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig

from lerobot.common.teleoperators import koch_leader, so100_leader, so101_leader  # noqa: F401


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class ControlConfig:
    # Resume recording on an existing dataset.
    resume: bool = True


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Control settings
    control: ControlConfig = None
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        if bool(self.teleop) == bool(self.policy):
            raise ValueError("Choose either a policy or a teleoperator to control the robot")

        # Initialize control config with defaults if not provided
        if self.control is None:
            self.control = ControlConfig()

        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


def load_hardware_config(config_path: str = "configs/hardware_config.json"):
    """Load hardware configuration from JSON file"""
    try:
        with open(config_path, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Hardware config file not found: {config_path}")
        exit(1)
    except json.JSONDecodeError:
        print(f"Invalid JSON in hardware config file: {config_path}")
        exit(1)


def load_dataset_config(config_path: str = "configs/last_dataset_config.json"):
    """Load dataset configuration from JSON file"""
    try:
        with open(config_path, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        default_config = {
            "dataset": {
                "repo_id": "",
                "single_task": "",
                "num_episodes": 50,
                "episode_time_s": 30,
                "reset_time_s": 10,
                "push_to_hub": True,
                "fps": 30,
                "video": True,
                "private": False,
                "num_image_writer_processes": 0,
                "num_image_writer_threads_per_camera": 4
            },
            "control": {
                "resume": True
            },
            "display_data": True,
            "play_sounds": True
        }
        save_dataset_config(default_config, config_path)
        return default_config
    except json.JSONDecodeError:
        print(f"Invalid JSON in dataset config file: {config_path}")
        exit(1)


def save_dataset_config(config: dict, config_path: str = "configs/last_dataset_config.json"):
    """Save dataset configuration to JSON file"""
    try:
        with open(config_path, 'w') as f:
            json.dump(config, f, indent=2)
    except Exception as e:
        print(f"Error saving dataset config: {e}")


def interactive_dataset_config(current_config: dict):
    """Interactive CLI for dataset configuration"""
    print("\n" + "="*60)
    print("DATASET CONFIGURATION")
    print("="*60)
    
    # Initialize control config if not present
    if "control" not in current_config:
        current_config["control"] = {"resume": True}
    
    print(f"Current values shown in [brackets]. Press Enter to keep current value.")
    print()
    
    # First question: Resume existing dataset?
    current_resume = current_config.get("control", {}).get("resume", True)
    resume_input = input(f"Resume existing dataset? (y/n) [{('y' if current_resume else 'n')}]: ").strip().lower()
    if resume_input in ['y', 'n']:
        current_config["control"]["resume"] = resume_input == 'y'
    
    # If resuming, skip most configuration questions
    if current_config["control"]["resume"]:
        print("\nResuming existing dataset. Only basic settings can be modified:")
        
        display_data = input(f"Display data during recording? (y/n) [{('y' if current_config['display_data'] else 'n')}]: ").strip().lower()
        if display_data in ['y', 'n']:
            current_config['display_data'] = display_data == 'y'
        
        play_sounds = input(f"Play sounds? (y/n) [{('y' if current_config['play_sounds'] else 'n')}]: ").strip().lower()
        if play_sounds in ['y', 'n']:
            current_config['play_sounds'] = play_sounds == 'y'
        
        return current_config
    
    # Full configuration for new datasets
    print("\nConfiguring new dataset:")
    dataset = current_config["dataset"].copy()
    
    repo_id = input(f"Dataset repository ID [{dataset['repo_id']}]: ").strip()
    if repo_id:
        dataset['repo_id'] = repo_id
    
    single_task = input(f"Task description [{dataset['single_task']}]: ").strip()
    if single_task:
        dataset['single_task'] = single_task
    
    try:
        num_episodes = input(f"Number of episodes [{dataset['num_episodes']}]: ").strip()
        if num_episodes:
            dataset['num_episodes'] = int(num_episodes)
        
        episode_time = input(f"Episode time (seconds) [{dataset['episode_time_s']}]: ").strip()
        if episode_time:
            dataset['episode_time_s'] = int(episode_time)
        
        reset_time = input(f"Reset time (seconds) [{dataset['reset_time_s']}]: ").strip()
        if reset_time:
            dataset['reset_time_s'] = int(reset_time)
        
        fps = input(f"FPS [{dataset['fps']}]: ").strip()
        if fps:
            dataset['fps'] = int(fps)
        
        processes = input(f"Image writer processes [{dataset.get('num_image_writer_processes', 0)}]: ").strip()
        if processes:
            dataset['num_image_writer_processes'] = int(processes)
        
        threads = input(f"Image writer threads per camera [{dataset.get('num_image_writer_threads_per_camera', 4)}]: ").strip()
        if threads:
            dataset['num_image_writer_threads_per_camera'] = int(threads)
    except ValueError:
        print("Invalid number entered. Using previous values.")
    
    push_to_hub = input(f"Push to hub? (y/n) [{('y' if dataset['push_to_hub'] else 'n')}]: ").strip().lower()
    if push_to_hub in ['y', 'n']:
        dataset['push_to_hub'] = push_to_hub == 'y'
    
    video = input(f"Record video? (y/n) [{('y' if dataset['video'] else 'n')}]: ").strip().lower()
    if video in ['y', 'n']:
        dataset['video'] = video == 'y'
    
    private = input(f"Private repository? (y/n) [{('y' if dataset['private'] else 'n')}]: ").strip().lower()
    if private in ['y', 'n']:
        dataset['private'] = private == 'y'
    
    display_data = input(f"Display data during recording? (y/n) [{('y' if current_config['display_data'] else 'n')}]: ").strip().lower()
    if display_data in ['y', 'n']:
        current_config['display_data'] = display_data == 'y'
    
    play_sounds = input(f"Play sounds? (y/n) [{('y' if current_config['play_sounds'] else 'n')}]: ").strip().lower()
    if play_sounds in ['y', 'n']:
        current_config['play_sounds'] = play_sounds == 'y'
    
    current_config["dataset"] = dataset
    
    # Validation for new datasets
    if not dataset['repo_id']:
        print("Error: Repository ID is required!")
        return None
    
    if not dataset['single_task']:
        print("Error: Task description is required!")
        return None
    
    return current_config


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | None = None,
    policy: PreTrainedPolicy | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    # if policy is given it needs cleaning up
    if policy is not None:
        policy.reset()

    timestamp = 0
    start_episode_t = time.perf_counter()
    print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: record_loop starting with control_time_s={control_time_s}, dataset={'None' if dataset is None else 'set'}")
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        observation = robot.get_observation()

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, observation, prefix="observation")

        if policy is not None:
            action_values = predict_action(
                observation_frame,
                policy,
                get_safe_torch_device(policy.config.device),
                policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )
            action = {key: action_values[i].item() for i, key in enumerate(robot.action_features)}
        else:
            action = teleop.get_action()

        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset.
        sent_action = robot.send_action(action)

        if dataset is not None:
            action_frame = build_dataset_frame(dataset.features, sent_action, prefix="action")
            frame = {**observation_frame, **action_frame}
            dataset.add_frame(frame, task=single_task)

        if display_data:
            for obs, val in observation.items():
                if isinstance(val, float):
                    rr.log(f"observation.{obs}", rr.Scalar(val))
                elif isinstance(val, np.ndarray):
                    rr.log(f"observation.{obs}", rr.Image(val), static=True)
            for act, val in action.items():
                if isinstance(val, float):
                    rr.log(f"action.{act}", rr.Scalar(val))

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t
        if events["exit_early"]:
            events["exit_early"] = False
            break
    
    actual_duration = time.perf_counter() - start_episode_t
    print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: record_loop finished after {actual_duration:.2f}s (target was {control_time_s}s)")


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        _init_rerun(session_name="recording")

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    action_features = hw_to_dataset_features(robot.action_features, "action", cfg.dataset.video)
    obs_features = hw_to_dataset_features(robot.observation_features, "observation", cfg.dataset.video)
    dataset_features = {**action_features, **obs_features}

    if cfg.control.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            )
        sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
    else:
        # Create empty dataset or load existing saved episodes
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
        )

    # Load pretrained policy
    policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)

    robot.connect()
    if teleop is not None:
        teleop.connect()

    listener, events = init_keyboard_listener()

    for recorded_episodes in range(cfg.dataset.num_episodes):
        log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
        record_loop(
            robot=robot,
            events=events,
            fps=cfg.dataset.fps,
            teleop=teleop,
            policy=policy,
            dataset=dataset,
            control_time_s=cfg.dataset.episode_time_s,
            single_task=cfg.dataset.single_task,
            display_data=cfg.display_data,
        )

        # Execute a few seconds without recording to give time to manually reset the environment
        # Skip reset for the last episode to be recorded
        if not events["stop_recording"] and (
            (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
        ):
            log_say("Reset the environment", cfg.play_sounds)
            print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: reset_time_s = {cfg.dataset.reset_time_s}")
            record_loop(
                robot=robot,
                events=events,
                fps=cfg.dataset.fps,
                teleop=teleop,
                control_time_s=cfg.dataset.reset_time_s,
                single_task=cfg.dataset.single_task,
                display_data=cfg.display_data,
            )

        if events["rerecord_episode"]:
            log_say("Re-record episode", cfg.play_sounds)
            events["rerecord_episode"] = False
            events["exit_early"] = False
            dataset.clear_episode_buffer()
            continue

        save_start_t = time.perf_counter()
        print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: Starting dataset.save_episode()")
        print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: Dataset config video: {cfg.dataset.video}")
        if hasattr(dataset, '_episode_buffer') and dataset._episode_buffer:
            buffer_size = len(dataset._episode_buffer)
            print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: Episode buffer size: {buffer_size}")
            # Try to get info about the data size
            if buffer_size > 0:
                sample_frame = dataset._episode_buffer[0]
                frame_keys = list(sample_frame.keys()) if isinstance(sample_frame, dict) else 'unknown'
                print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: Sample frame keys: {frame_keys}")
        else:
            print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: Episode buffer size: unknown")
        
        # Add timing around the actual save_episode call
        pre_save_t = time.perf_counter()
        print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: About to call dataset.save_episode()...")
        dataset.save_episode()
        post_save_t = time.perf_counter()
        print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: dataset.save_episode() internal call completed")
        
        save_duration = post_save_t - save_start_t
        print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: dataset.save_episode() completed in {save_duration:.2f}s")

        if events["stop_recording"]:
            break

    cleanup_start_t = time.perf_counter()
    print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: Starting cleanup operations")
    
    log_say("Stop recording", cfg.play_sounds, blocking=True)

    disconnect_start_t = time.perf_counter()
    robot.disconnect()
    teleop.disconnect()
    disconnect_duration = time.perf_counter() - disconnect_start_t
    print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: Robot/teleop disconnect completed in {disconnect_duration:.2f}s")

    if not is_headless() and listener is not None:
        listener.stop()

    if cfg.dataset.push_to_hub:
        push_start_t = time.perf_counter()
        print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: Starting push_to_hub")
        dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)
        push_duration = time.perf_counter() - push_start_t
        print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: push_to_hub completed in {push_duration:.2f}s")

    cleanup_duration = time.perf_counter() - cleanup_start_t
    print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: Total cleanup completed in {cleanup_duration:.2f}s")
    
    log_say("Exiting", cfg.play_sounds)
    print(f"DEBUG [{datetime.now().strftime('%H:%M:%S')}]: Program exiting")
    return dataset


def main():
    """Main function with config file loading and interactive CLI"""
    print("="*60)
    print("LeRobot Episode Recorder")
    print("="*60)
    
    # Load hardware configuration
    print("Loading hardware configuration...")
    hw_config = load_hardware_config()
    
    print(f"Robot: {hw_config['robot']['type']} ({hw_config['robot']['id']})")
    print(f"Port: {hw_config['robot']['port']}")
    print(f"Cameras: {list(hw_config['robot']['cameras'].keys())}")
    print(f"Teleop: {hw_config['teleop']['type']} ({hw_config['teleop']['id']})")
    print(f"Teleop Port: {hw_config['teleop']['port']}")
    
    # Load dataset configuration
    print("\nLoading dataset configuration...")
    dataset_config = load_dataset_config()
    
    # Interactive dataset configuration
    print("\nConfigure dataset parameters...")
    updated_config = interactive_dataset_config(dataset_config)
    
    if updated_config is None:
        print("Configuration cancelled.")
        return
    
    # Save updated configuration
    save_dataset_config(updated_config)
    print("\nDataset configuration saved.")
    
    # Preview final configuration
    print("\n" + "="*60)
    print("FINAL CONFIGURATION")
    print("="*60)
    
    print("Hardware:")
    print(f"  Robot: {hw_config['robot']['type']} on {hw_config['robot']['port']}")
    print(f"  Teleop: {hw_config['teleop']['type']} on {hw_config['teleop']['port']}")
    print(f"  Cameras: {list(hw_config['robot']['cameras'].keys())}")
    
    print("\nDataset:")
    dataset = updated_config['dataset']
    print(f"  Repository: {dataset['repo_id']}")
    print(f"  Task: {dataset['single_task']}")
    print(f"  Episodes: {dataset['num_episodes']}")
    print(f"  Episode time: {dataset['episode_time_s']}s")
    print(f"  Reset time: {dataset['reset_time_s']}s")
    print(f"  Push to hub: {dataset['push_to_hub']}")
    print(f"  Image writer processes: {dataset.get('num_image_writer_processes', 0)}")
    print(f"  Image writer threads per camera: {dataset.get('num_image_writer_threads_per_camera', 4)}")
    print(f"  Display data: {updated_config['display_data']}")
    
    # Confirm start
    print("\n" + "-"*60)
    confirm = input("Start recording? (y/n): ").strip().lower()
    if confirm != 'y':
        print("Recording cancelled.")
        return
    
    # Build command arguments
    import sys
    
    # Override sys.argv to pass configuration to the original record function
    original_argv = sys.argv.copy()
    
    sys.argv = [
        "record_episodes.py",
        f"--robot.type={hw_config['robot']['type']}",
        f"--robot.port={hw_config['robot']['port']}",
        f"--robot.id={hw_config['robot']['id']}",
        f"--robot.cameras={json.dumps(hw_config['robot']['cameras'])}",
        f"--teleop.type={hw_config['teleop']['type']}",
        f"--teleop.port={hw_config['teleop']['port']}",
        f"--teleop.id={hw_config['teleop']['id']}",
        f"--dataset.repo_id={dataset['repo_id']}",
        f"--dataset.single_task={dataset['single_task']}",
        f"--dataset.num_episodes={dataset['num_episodes']}",
        f"--dataset.episode_time_s={dataset['episode_time_s']}",
        f"--dataset.reset_time_s={dataset['reset_time_s']}",
        f"--dataset.push_to_hub={'true' if dataset['push_to_hub'] else 'false'}",
        f"--dataset.fps={dataset['fps']}",
        f"--dataset.video={'true' if dataset['video'] else 'false'}",
        f"--dataset.private={'true' if dataset['private'] else 'false'}",
        f"--dataset.num_image_writer_processes={dataset.get('num_image_writer_processes', 0)}",
        f"--dataset.num_image_writer_threads_per_camera={dataset.get('num_image_writer_threads_per_camera', 4)}",
        f"--control.resume={'true' if updated_config.get('control', {}).get('resume', True) else 'false'}",
        f"--display_data={'true' if updated_config['display_data'] else 'false'}",
        f"--play_sounds={'true' if updated_config['play_sounds'] else 'false'}"
    ]
    
    try:
        print("\nStarting recording...")
        record()
    finally:
        sys.argv = original_argv


if __name__ == "__main__":
    main()
